---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  selector:
    matchLabels:
      app: react
  replicas: 2
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: onedev.mazilious-tower.duckdns.org/nextjs-test/nextsjs-testt:latest 
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-servce
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 3000